/**
 * Copyright (c) 2025 Luca Visciola
 * SPDX-License-Identifier: MIT
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// seed-redis.ts
import { hash } from 'bcryptjs';
import { UserRepository } from '~/server/utils/auth/user-repository';
import { PostRepository } from '~/server/repositories/PostRepository';
import { getRedisClient } from '~/scripts/cli/utils/redis-client';

async function seedRedis() {
    const redis = await getRedisClient();

    try {
        if (!redis.isOpen) {
            await redis.connect();
            console.log('Connected to Redis');
        }

        // Clear existing data for a fresh seed
        await redis.flushAll();
        console.log('Cleared all existing Redis data.');

        // --- Create Default Admin User ---
        const defaultAdminUsername = process.env.DEFAULT_ADMIN_USERNAME || 'admin';
        const defaultAdminPassword = process.env.DEFAULT_ADMIN_PASSWORD || 'password';
        if (!process.env.DEFAULT_ADMIN_PASSWORD) {
            console.warn('⚠️ WARNING: Using default admin password. Please set DEFAULT_ADMIN_PASSWORD environment variable for production.');
        }
        const defaultAdminEmail = process.env.DEFAULT_ADMIN_EMAIL || 'admin@example.com';

        const cliUserRepository = new UserRepository(getRedisClient);

        const existingAdmin = await cliUserRepository.getByUsername(defaultAdminUsername);
        if (!existingAdmin) {
            const passwordHash = await hash(defaultAdminPassword, 10);
            await cliUserRepository.create({
                username: defaultAdminUsername,
                email: defaultAdminEmail,
                passwordHash: passwordHash,
                roles: ['admin'],
            });
            console.log(`Seeded default admin user: "${defaultAdminUsername}"`);
        } else {
            console.log(`Admin user "${defaultAdminUsername}" already exists.`);
        }

        // --- Create Example Posts using the Repository ---
        const postRepository = new PostRepository(getRedisClient);

        const examplePosts = [
            {
                title: 'Welcome to Your New Redis Nuxt Blog!',
                content: `
# Welcome to Your New Blog!

This is your first post, generated by the seed script. This boilerplate is a powerful starting point for building a high-performance, deeply customizable blog with **Nuxt.js** and **Redis Stack**.

## Core Philosophy

The goal of this project is to provide a solid foundation that is both easy to use and easy to extend. Here are the core principles:

- **Performance First:** Built with Nuxt for server-side rendering and Redis for ultra-fast data access.
- **Deeply Customizable:** Almost every aspect of the blog, from fonts and colors to features like pagination, can be configured from a single file.
- **Developer-Friendly:** A clean, modern tech stack with Docker for a consistent environment and a CLI for managing posts.

## What's Included?

*   🚀 Nuxt.js 3 Frontend & API
*   ⚡ Redis Stack as the Primary Database (using RedisJSON)
*   🎨 Customizable Theming via 
config/blog.config.ts
*   📝 **Markdown Support** for writing posts.
*   ⚙️ Feature Toggles for pagination, post navigation, and excerpts.
*   📦 A fully Dockerized environment.

Feel free to delete this post and start writing your own amazing content!
                `,
                author: 'Boilerplate Bot',
                tags: ['welcome', 'nuxt', 'redis'],
                excerpt: 'This is your first post, generated by the seed script. This boilerplate is a powerful starting point for building a high-performance, deeply customizable blog with Nuxt.js and Redis Stack.',
                featured_image: '/images/redis-blog-poster-image.jpg',
            },
            {
                title: 'Deeply Customize Your Blog in Minutes',
                content: `
# Customize Your Blog's Look and Feel

One of the key features of this boilerplate is its deep customizability, managed from a single file: 
config/blog.config.ts
.

## Changing Fonts and Colors

You can define your blog's entire visual identity by modifying the 
typography
 and 
colors
 objects.

\`\`\`typescript
// config/blog.config.ts
export const defaultBlogConfig = {
  // ...
  typography: {
    body: { fontFamily: 'Inter', weights: '400..700', italic: true },
    h1: { fontFamily: 'Poppins', weights: '700' },
    // ...
  },
  colors: {
    primary: '#ff5733',
    secondary: '#5c6ac4',
    text: '#333333',
    background: '#f8f9fa',
  },
};
\`\`\`

## Toggling Features

Easily enable or disable major features like pagination, post navigation, or the new post excerpts.

\`\`\`typescript
// config/blog.config.ts
export const defaultBlogConfig = {
    // ...
    pagination: {
        enabled: true,
        postsPerPage: 5,
    },
    postNavigation: {
        enabled: true,
    },
    postExcerpt: {
        enabled: true,
        maxLength: 200,
    },
    // ...
};
\`\`\`

Simply update the file, and your changes will be reflected instantly in your development environment after a server restart.
                `,
                author: 'Boilerplate Bot',
                tags: ['customization', 'theming', 'config', 'tutorial'],
                excerpt: 'Learn how to deeply customize your blog\'s look, feel, and features in minutes by modifying a single configuration file: config/blog.config.ts.',
                featured_image: '/images/redis-blog-the-ultimate-tech-stack.jpg',
            },
        ];

        for (const postData of examplePosts) {
            const createdAt = Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000;

            const newPostData = {
                title: postData.title,
                content: postData.content,
                excerpt: postData.excerpt,
                featured_image: postData.featured_image,
                author: postData.author,
                tags: postData.tags,
                createdAt,
            };

            const createdPost = await postRepository.createPost(newPostData);
            console.log(`Seeded post: "${createdPost.title}" with id "${createdPost.id}"`);
        }

        console.log('Redis seeding complete!');
        await redis.save();
        console.log('Redis data saved to disk.');
    } catch (error) {
        console.error('Failed to seed Redis:', error);
    } finally {
        await redis.disconnect();
        console.log('Disconnected from Redis');
    }
}

seedRedis();
