// seed-redis.ts
import { createClient } from 'redis';
import * as dotenv from 'dotenv';
// No Post import needed for tsx runtime when creating posts
// No getRedis import needed

dotenv.config(); // Load environment variables from .env file

// Simple slugify function
function slugify(text: string): string {
    return text
        .toString()
        .toLowerCase()
        .replace(/\s+/g, '-') // Replace spaces with -
        .replace(/[^\w\-]+/g, '') // Remove all non-word chars
        .replace(/\-\-+/g, '-') // Replace multiple - with one -
        .replace(/^-+/, '') // Trim - from start
        .replace(/-+$/, ''); // Trim - from end
}

async function seedRedis() {
    const redisUrl = process.env.NUXT_REDIS_URL || 'redis://localhost:6380';
    const redis = createClient({ url: redisUrl }); // Directly create client

    redis.on('error', (err) => console.error('Redis Client Error', err));

    try {
        await redis.connect();
        console.log('Connected to Redis');

        // Clear existing data for a fresh seed
        await redis.flushAll();
        console.log('Cleared all existing Redis data.');

        const examplePosts = [
            {
                title: 'Welcome to Your New Redis Nuxt Blog!',
                content: `
# Welcome to Your New Blog!

This is your first post, generated by the seed script. This boilerplate is a powerful starting point for building a high-performance, deeply customizable blog with **Nuxt.js** and **Redis Stack**.

## Core Philosophy

The goal of this project is to provide a solid foundation that is both easy to use and easy to extend. Here are the core principles:

- **Performance First:** Built with Nuxt for server-side rendering and Redis for ultra-fast data access.
- **Deeply Customizable:** Almost every aspect of the blog, from fonts and colors to features like pagination, can be configured from a single file.
- **Developer-Friendly:** A clean, modern tech stack with Docker for a consistent environment and a CLI for managing posts.

## What's Included?

*   🚀 Nuxt.js 3 Frontend & API
*   ⚡ Redis Stack as the Primary Database (using RedisJSON)
*   🎨 Customizable Theming via \`config/blog.config.ts\`
*   📝 **Markdown Support** for writing posts.
*   ⚙️ Feature Toggles for pagination, post navigation, and excerpts.
*   📦 A fully Dockerized environment.

Feel free to delete this post and start writing your own amazing content!
                `,
                author: 'Boilerplate Bot',
                tags: ['welcome', 'nuxt', 'redis'],
                excerpt: 'This is your first post, generated by the seed script. This boilerplate is a powerful starting point for building a high-performance, deeply customizable blog with Nuxt.js and Redis Stack.',
                image: '/images/redis-blog-poster-image.jpg',
            },
            {
                title: 'Deeply Customize Your Blog in Minutes',
                content: `
# Customize Your Blog's Look and Feel

One of the key features of this boilerplate is its deep customizability, managed from a single file: \`config/blog.config.ts\`.

## Changing Fonts and Colors

You can define your blog's entire visual identity by modifying the \`typography\` and \`colors\` objects.

\`\`\`typescript
// config/blog.config.ts
export const defaultBlogConfig = {
  // ...
  typography: {
    body: { fontFamily: 'Inter', weights: '400..700', italic: true },
    h1: { fontFamily: 'Poppins', weights: '700' },
    // ...
  },
  colors: {
    primary: '#ff5733',
    secondary: '#5c6ac4',
    text: '#333333',
    background: '#f8f9fa',
  },
};
\`\`\`

## Toggling Features

Easily enable or disable major features like pagination, post navigation, or the new post excerpts.

\`\`\`typescript
// config/blog.config.ts
export const defaultBlogConfig = {
    // ...
    pagination: {
        enabled: true,
        postsPerPage: 5,
    },
    postNavigation: {
        enabled: true,
    },
    postExcerpt: {
        enabled: true,
        maxLength: 200,
    },
    // ...
};
\`\`\`

Simply update the file, and your changes will be reflected instantly in your development environment after a server restart.
                `,
                author: 'Boilerplate Bot',
                tags: ['customization', 'theming', 'config', 'tutorial'],
                excerpt: 'Learn how to deeply customize your blog\'s look, feel, and features in minutes by modifying a single configuration file: config/blog.config.ts.',
            },
            {
                title: 'Writing Posts with Markdown',
                content: `
# Mastering Content with Markdown

This blog fully supports writing posts in Markdown, allowing you to create rich, formatted content with ease.

## Creating a Post

To create a new post, run the following command in your terminal:

\`\`\`bash
npm run new-post
\`\`\`

You will be prompted for a title, tags, and author. For the content, you can write multi-line Markdown. When you're finished, type **(end)** on a new line to save the post.

## Markdown Examples

Here’s a quick demonstration of what you can do:

### Text Formatting

You can use *italics*, **bold**, and \`inline code\`.

### Lists

- Unordered List Item 1
- Unordered List Item 2

1.  Ordered List Item 1
2.  Ordered List Item 2

### Code Blocks

You can also include syntax-highlighted code blocks:

\`\`\`javascript
// Example of a JavaScript function
function greet(name) {
  console.log(\`Hello, \${name}!\`);
}
\`\`\`

This makes it easy to write technical articles and tutorials.
                `,
                author: 'Boilerplate Bot',
                tags: ['markdown', 'writing', 'cli', 'tutorial'],
                excerpt: 'This blog fully supports writing posts in Markdown, allowing you to create rich, formatted content with ease. Learn how to create and format your posts.',
            },
            {
                title: 'Under the Hood: Architecture Overview',
                content: `
# The Redis & Nuxt Architecture

Ever wondered how this boilerplate works? Here’s a high-level look at the architecture.

## The Stack

- **Nuxt.js 3:** Acts as both the frontend framework (Vue.js) and the backend API server (using Nitro).
- **Redis Stack:** Serves as the primary database.
  - **RedisJSON:** Stores each post as a JSON document, allowing for flexible and structured data.
  - **Redis Sorted Sets:** Used to maintain a chronological index of posts (\`posts:by_date\`), making timeline queries extremely fast.
- **Docker:** Containerizes the entire application for a consistent and reproducible environment.

## Data Flow

1.  A user requests a page (e.g., the homepage).
2.  The Nuxt frontend calls an internal API route (e.g., \`/api/posts\`).
3.  The API route in \`/server/api/\` connects to Redis.
4.  It fetches the post keys from the \`posts:by_date\` sorted set.
5.  It then retrieves the full post data for each key using RedisJSON commands.
6.  The data is returned to the frontend, rendered into HTML, and served to the user.

This architecture is designed for speed, scalability, and ease of development.
                `,
                author: 'Boilerplate Bot',
                tags: ['architecture', 'technical', 'nuxt', 'redis', 'redisjson'],
                excerpt: 'A high-level overview of the Redis and Nuxt architecture powering this blog boilerplate, detailing the stack and data flow.',
            },
             {
                title: 'Deploying Your Blog to Production',
                content: `
# From Development to Production

Taking your blog live requires a few key steps. This guide provides a general overview.

## Environment Variables

Before deploying, ensure you have a \`.env\` file for your production environment. Copy \`.env.example\` and fill in the values for your production Redis instance and domain.

## Using Docker Compose for Production

This boilerplate includes a production-ready Docker Compose file.

\`\`\`bash
docker compose -f docker-compose.prod.yml up -d --build
\`\`\`

This command builds the Nuxt application in production mode and runs it in a container, connecting it to your Redis instance.

## Key Considerations

- **Hosting:** You'll need a server or service that can run Docker containers (e.g., DigitalOcean, AWS EC2, or a similar VPS).
- **Redis Provider:** While you can host Redis yourself, consider using a managed service like Redis Enterprise Cloud for scalability and reliability.
- **CI/CD:** For automated deployments, set up a CI/CD pipeline (e.g., using GitHub Actions) to automatically build and deploy your application whenever you push changes.
                `,
                author: 'Boilerplate Bot',
                tags: ['deployment', 'production', 'docker', 'devops'],
                excerpt: 'A guide to deploying your Redis Nuxt blog to production, covering environment variables, Docker Compose, and key deployment considerations.',
            },
            {
                title: 'A New Stack: Introducing Redis Nuxt Blog — A Sci-Fi Blog Boilerplate',
                content: `

# ✨ _A New Stack_ — Introducing **Redis Nuxt Blog**: A Sci-Fi Blog Boilerplate from a Galaxy Not So Far Away

> _“A long time ago, in a server rack far, far away, a lone developer sought a faster way to publish their thoughts across the galaxy…”_

If you’re a developer roaming the cosmic void in search of the perfect blogging platform — one fast enough to outrun hyperspace lag, simple enough to configure from a single holocron file, and powered by the mighty Force of Redis — your quest ends here.

Welcome to **Redis Nuxt Blog**, a futuristic, high-performance boilerplate forged with **Nuxt 3**, **Redis Stack**, and a containerized fleet of **Docker Star Destroyers**.  
Inspired by the legendary _Salvatore “antirez” Sanfilippo_, creator of Redis and intergalactic craftsman of absurdly fast data structures, this project aims to honor that sci-fi spirit — equal parts elegance, speed, and space-wizardry.

Grab your lightsabers, devs. We’re jumping to lightspeed. 🚀⚡

![Redis Nuxt Blog](https://raw.githubusercontent.com/melasistema/redis-blog/master/resources/images/redis-blog-poster-image.jpg)

----------

## 🌌 Why Another Blog Boilerplate?

Because most blog starters are like broken droids — sluggish, uncustomizable, and likely to beep something rude at you when you change a font.

**Redis Nuxt Blog** is built for developers who want:

-   A fast, SSR-friendly, SEO-happy front-end
    
-   A database engine so quick it would embarrass a pod-racer
    
-   A deeply configurable UI without fiddling with 27 separate config files
    
-   A ready-to-launch Docker setup
    
-   A CLI so efficient it feels like talking to R2-D2 (but without the panic screams)
    
-   **A theming system powered by Tailwind CSS, customizable from one file**
    
-   **Markdown-powered post content**
    
-   **Dynamic excerpts and content width control**
    

----------

## ✨ Core Features (Translated from Wookiee)

### 🚀 Nuxt.js 3 Frontend

Modern. Fast. SSR-powered.  
Perfect for blogs, portals, and broadcasting your galactic manifestos.

### ⚡ Redis Stack as the Primary Database

Forget SQL. Forget slow disks.  
We harness the **Quantum Hyperdrive** (a.k.a RedisJSON + Redis Sorted Sets) to store posts with blazing speed.

Salvatore Sanfilippo didn’t intend Redis to be a sci-fi artifact… but let’s be honest, it might as well have been forged from midichlorians.

![Redis Nuxt Blog](https://raw.githubusercontent.com/melasistema/redis-blog/master/resources/images/redis-blog-hyperdrive-performance.jpg)

### 🎨 One Config File to Rule Them All (Now With Full Tailwind Integration)

Every visual setting — fonts, weights, palette, spacing, even content width — comes from:

\`config/blog.config.ts\` 

This single file now controls:

-   Typography per heading level
    
-   Full Tailwind color palette generation
    
-   Global content max-width
    
-   Header title & tagline
    
-   Layout constraints
    

Balance to the styling Force, at last.

### ✂️ Post Excerpts (New!)

Enable **post previews** on the homepage with:

-   \`postExcerpt.enabled\`
    
-   \`postExcerpt.maxLength\`
    

Perfect for teasing your readers like a Holonet trailer.

### ↔️ Post Navigation

Navigate between posts like browsing encrypted Jedi archives.

### 📝 Markdown Support

Posts are fully Markdown-powered — headings, lists, code blocks, even multi-line input via CLI.

Write your galactic knowledge in pure Markdown. No HTML acrobatics needed.

### 📦 Dockerized Everything

Spin up Nuxt + Redis with one command:

\`docker compose up -d --build\` 

Your dev environment becomes as consistent as Stormtrooper aim (but… good).

### 📜 Content CLI (Upgraded!)

Create, list, delete posts with simple commands:

\`npm run new-post
npm run post:list
npm run post:delete\` 

The CLI now supports:

-   Multi-line Markdown input
    
-   Automatically generated slugs
    
-   Default author fallback
    

You are now the administrator of your own Holocron Library.

----------

## 🛰️ Tech Stack: What Our Starship Is Made Of

-   **Nuxt 3** — the elegant lightsaber
    
-   **Redis Stack w/ RedisJSON** — the hyperdrive core
    
-   **Tailwind CSS** — the robe of a modern Jedi developer
    
-   **Google Fonts module** — for typographic wizardry
    
-   **Docker Compose** — the Imperial Fleet
    
-   **TypeScript + tsx runtime** — because even smugglers need types


![Redis Nuxt Blog](https://raw.githubusercontent.com/melasistema/redis-blog/master/resources/images/redis-blog-the-ultimate-tech-stack.jpg)
    

----------

## 🛠️ The Holocron of Configuration (Updated!)

Everything — fonts, colors, layout, excerpts, pagination — lives in:

\`config/blog.config.ts\` 

New additions include:

-   \`headerTitle\`
    
-   \`headerTagline\`
    
-   Dynamic Tailwind theme generation
    
-   \`contentMaxWidth\`
    
-   Post excerpts config
    

Want your blog to have an imperial blue palette?  
Done.

Want H1 in _Englebert_ and H2 in _Roboto Slab_?  
Absolutely.

Want your content width to feel like the inside of a Star Destroyer corridor?  
Just set a new max-width.

----------

## 🔌 API Endpoints (For the Droids Among Us)

| Endpoint | Method | Description |
| -------- | -----  | ----------- |
| \`/api/posts\` | GET | Retrieve posts. Supports \`?page=N\` |
| \`/api/posts/:slug\` | GET | Fetch single post + neighbors |
| \`/api/tags\` | GET | Retrieve all tags |

Perfect for custom frontends, mobile apps, or your own droid companion.

----------

## 🪐 Why Developers Love This

Because **simplicity** + **power** = developer bliss.

Because Redis is a piece of sci-fi technology disguised as a database.

Because Nuxt 3 is smooth as sliding through hyperspace.

Because Tailwind lets you customize everything without rewriting CSS.

Because Markdown posts feel like writing Jedi scrolls.

And because every post stored in Redis Sorted Sets is basically organized by the Force.

----------

## 👤 Author & Origin Story

Built by **[Luca Visciola](https://github.com/melasistema)** — drummer, developer, and happy dad.

Inspired by **[Salvatore “antirez” Sanfilippo](https://antirez.com)**, whose creation Redis is widely believed to be running not on silicon… but on compressed fragments of a neutron star.

----------

## 🛸 Final Transmission

If you're searching for a fast, flexible, sci-fi-friendly blog engine that handles posts faster than the Millennium Falcon outruns TIE Fighters, this boilerplate may be the one you’re looking for.

Clone it.  
Customize it.  
Seed it.  
Deploy it.

👉 **GitHub Repository:**  
**[https://github.com/melasistema/redis-blog](https://github.com/melasistema/redis-blog)**

And may the **Force of Redis** be with you. ❤️‍🔥
`,
                author: 'Luca Visciola',
                tags: ['announcement', 'release', 'nuxt', 'redis', 'blog'],
                excerpt: `If you're a developer roaming the cosmic void in search of the perfect blogging platform — one fast enough to outrun hyperspace lag, simple enough to configure from a single holocron file, and powered by the mighty Force of Redis — your quest ends here.`,
                image: '/images/redis-blog-poster-image.jpg',
            }
        ];

        for (const postData of examplePosts) {
            const slug = slugify(postData.title);

            // If this is the special Dev.to article → force newest timestamp
            const isFeatured = postData.title.startsWith('A New Stack: Introducing Redis Nuxt Blog');

            const createdAt = isFeatured
                ? Date.now() // always newest post
                : Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000; // random timestamp within last 30 days

            const post = {
                slug,
                title: postData.title,
                content: postData.content,
                excerpt: postData.excerpt || postData.content.substring(0, 150), // Use provided excerpt or generate
                image: postData.image, // Use provided image
                author: postData.author,
                tags: postData.tags,
                createdAt,
            };

            const postKey = `post:${slug}`; // Use slug for postKey

            const multi = redis.multi();
            multi.json.set(postKey, '$', post as any);
            multi.zAdd('posts:by_date', {
                score: createdAt,
                value: postKey,
            });
            multi.hSet('slugs', slug, postKey);

            // Add tags to global and tag-specific SETs
            if (post.tags?.length) {
                for (const tag of post.tags) {
                    multi.sAdd('tags:all', tag);
                    multi.sAdd(`tag:${slugify(tag)}`, postKey);
                }
            }

            await multi.exec();
            console.log(`Seeded post: "${post.title}" with key "${postKey}"`);
        }

        console.log('Redis seeding complete!');
        await redis.save();
        console.log('Redis data saved to disk.');
    } catch (error) {
        console.error('Failed to seed Redis:', error);
    } finally {
        await redis.disconnect();
        console.log('Disconnected from Redis');
    }
}

seedRedis();
